import Head from "next/head";
import {UserTaskList} from "@/components/task/components/UserTaskList";
import {useUser} from "@/components/user-authentication/hooks/useUser";
import {InitFilter} from "@/components/task/components/Preference/InitFilter";
import {EventFilterStyles, ListHeader} from "@/components/task/styles/TaskFilterStyles";
import {TopicFilter} from "@/components/task/components/Preference/TopicFilter";
import {ResetPreferenceFilter} from "@/components/task/components/Preference/ResetPreferenceFilter";

export default function Home() {
    const user = useUser()

    if (!user) return null

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <>
            {(user.topicPreference !== undefined) &&  (<>
                <ListHeader>
                    <EventFilterStyles>
                        <TopicFilter/>
                        <ResetPreferenceFilter/>
                    </EventFilterStyles>
                    <UserTaskList />
                </ListHeader>
            </>)
            }
            {(user.topicPreference === undefined) &&  (<>
                <InitFilter />
            </>)
            }
        </>


    </>
  );
}
